# Generated by Django 3.0.2 on 2020-01-08 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('1', 'Beginner (8x8 with 10 mines)'), ('2', 'Intermediate (16x16 with 40 mines)'), ('3', 'Expert (16x30 with 99 mines)')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAIL', 'Failed'), ('ABORT', 'Aborted'), ('ERROR', 'An Error Occurred'), ('UNKNOWN', 'Unknown Status')], default=None, max_length=10, null=True)),
                ('bombs_flagged', models.IntegerField(blank=True, default=0, null=True)),
                ('time_elapsed', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
