# Generated by Django 3.0.2 on 2020-01-07 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAIL', 'Failed'), ('ERROR', 'An Error Occurred'), ('UNKNOWN', 'Unknown Status')], max_length=10, null=True)),
                ('bombs_revealed', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, db_index=True, null=True)),
                ('time_elapsed', models.IntegerField(blank=True, null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
